---
- name: Copy the NGINX repository definition
  copy: src=nginx.repo dest=/etc/yum.repos.d/

- name: Create the GPG key for NGINX
  copy: src=RPM-GPG-KEY-NGINX dest=/etc/pki/rpm-gpg

- name: Install Firewalld
  yum: name=firewalld state=present

- name: Firewalld service state
  service: name=firewalld state=started enabled=yes
